# Generated by Django 5.2.5 on 2026-04-22 08:09

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.get_path_for_category
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.get_path_for_server
            ),
        ),
    ]
